#!/usr/bin/env python

"""
    Displays a list of the recently played songs on Q107 FM.
    Usage: q107 [numSongs]

    Copyright 2010 Alex Margarit

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import sys, re

if sys.version_info[0] > 2:
    from urllib.request import urlopen
else:
    from urllib import urlopen

def songs(num):
    site = urlopen("http://www.q107.com/BroadcastHistory.aspx")
    content = site.read()
    site.close()

    pattern = b'<td class="timeStamp dim txtMini">(.*?)</td>.*?<td class="broadcast txtMini" width="90%">.*?<span>(.*?)</span>.*?</td>'
    songs = re.finditer(pattern, content, re.DOTALL)

    count = 0

    for s in songs:
        count += 1

        if count > num:
            break

        time = s.group(1).strip().rjust(8).decode()
        song = s.group(2).strip().decode()

        print(time + " " + song)

if __name__ == "__main__":
    if len(sys.argv) == 2:
        songs(int(sys.argv[1]))
    else:
        songs(5)
