#!/usr/bin/python

"""
    Displays a list of the recently played songs on Q107 FM.
    Usage: y108 [numSongs]

    Copyright 2010 Alex Margarit

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import sys, re, urllib

def songs(num):
    site = urllib.urlopen("http://www.y108.ca/NowPlaying/Songs.aspx")
    content = site.read()
    site.close()

    pattern = '<td class="timeStamp dim txtMini">(.*?)</td>.*?<td class="broadcast txtMini" width="90%">.*?<span>(.*?)</span>.*?</td>'
    songs = re.finditer(pattern, content, re.DOTALL)

    for s in range(0, num):
        try:
            song = songs.next()
            print "%8s %s" % (song.group(1).strip(), song.group(2).strip())
        except StopIteration:
            break

if __name__ == "__main__":
    if len(sys.argv) == 2:
        songs(int(sys.argv[1]))
    else:
        songs(5)
